export const backendURL = 'http://localhost:5000'

export const singers = [
  {
    id: '0',
    name: '村花0',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
  {
    id: '1',
    name: '村花1',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
  {
    id: '2',
    name: '村花2',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
  {
    id: '3',
    name: '村花3',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
  {
    id: '4',
    name: '村花4',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
  {
    id: '5',
    name: '村花5',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
  {
    id: '6',
    name: '村花6',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
  {
    id: '7',
    name: '村花7',
    photo: 'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png',
    description: '巴村 村花',
    songName: '山歌',
    cardStyle: { width: '100%', textAlign: 'center' },
    isLike: false,
  },
]
